name: ecco_link_example
description: An example application for Ecco's ecco_lint package

publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ecco: ^0.0.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ecco_lint:
    path: ../
