name: ecco_lint
description: A custom lint package for the Ecco state management framework in Flutter
version: 0.0.1+3
homepage: https://github.com/permadart/ecco
repository: https://github.com/permadart/ecco/tree/main/packages/ecco_lint
issue_tracker: https://github.com/permadart/ecco/issues

environment:
  sdk: ^3.5.1

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  collection: ^1.18.0
  custom_lint_builder: ^0.6.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ecco: ^0.0.1+7
