name: ecco
description: A simple, MVVM-focused state management solution for Flutter.
version: 0.0.1+7
homepage: https://github.com/permadart/ecco
repository: https://github.com/permadart/ecco/tree/main/packages/ecco
issue_tracker: https://github.com/permadart/ecco/issues

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
